# Generated by Django 2.2.11 on 2020-04-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=20000)),
                ('date_create', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Políticas de privacidad',
            },
        ),
        migrations.CreateModel(
            name='TermsCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=20000)),
                ('date_create', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Términos y condiciones',
            },
        ),
    ]
