EMAIL_SITE = 'ssss@gmail.com'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_SITE
SERVER_EMAIL = EMAIL_SITE
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = EMAIL_SITE
EMAIL_HOST_PASSWORD = 'xxx'